### PR TITLE
chore: Editing i18n name on docs

### PR DESCRIPTION
**Pull request by victor-heliomar**
## Overview

Updated all mentions to the project on the doc to the new name. This PR also updates the config file name from `i18n-auto-translate.config.js` to `i18n-populator.config.js` which is a name easier to remember and write

### CODE REVIEW

**Review by Israel-Laguan — APPROVED** [review]
Not sure if package.json need to change too?

**Comment by victor-heliomar** [comment]
> Not sure if package.json need to change too?

Already changed

Captura de pantalla 2024-06-06 a la(s) 7 26 42 a  m

**Review by YoelFerreyra — APPROVED** [review]
Approve

**Comment by victor-heliomar** [comment]
Thanks for reviews!

**Pull request merged**
